spring:
  h2:
    console:
      enabled: true
#  datasource:
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12A402?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    username: S09P12A402
#    password: vHsB2D5Bjk
#    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: profile, email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: ${JWT_SECRET}

client:
  host: i9a402.p.ssafy.io
  url: https://i9a402.p.ssafy.io
  endpoint: success

cloud:
  aws:
    s3:
      bucket: corookie.sss
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

web-client:
  vito-api:
    access-key : ${VITO_ACCESS_KEY}
    secret-access-key : ${VITO_SECRET_KEY}

ai-service:
  domain : ${AI_DOMAIN}